import { testimonial } from "../types/testimonial";

export const testimonials: testimonial[] = [
  {
    rating: 5,
    title: "Exceptional Service!",
    body: "Our experience with Estatein was outstanding. Their team's dedication and professional is made finding our dream home a breeze. Highly recommended!",
    name: "Wade Warren",
    location: "USA, California",
    avatar: "/avatars/wade-warren.webp",
  },

  {
    rating: 5,
    title: "Smooth Transaction",
    body: "We can't say enough good things about Estatein. They guided us through every step and negotiated a great price on our new home.",
    name: "Lawrence Arnold",
    location: "Canada, Toronto",
    avatar: "/avatars/lawrence-arnold.webp",
  },
  {
    rating: 5,
    title: "Knowledgeable and Helpful",
    body: "The team at Estatein made finding and purchasing our first home easy. Their expertise and responsiveness were much appreciated.",
    name: "Manuel Simpson",
    location: "UK, London",
    avatar: "/avatars/manuel-simpson.webp",
  },
  {
    rating: 5,
    title: "Stress-Free Experience",
    body: "With Estatein's help, we found the perfect home and closed quickly and smoothly. We highly recommend their services.",
    name: "Robert Gomez",
    location: "Australia, Sydney",
    avatar: "/avatars/robert-gomez.webp",
  },
  {
    rating: 5,
    title: "Exceeded Expectations",
    body: "Estatein went above and beyond to ensure we found the right home. Their dedication and attention to detail were unmatched.",
    name: "Harry Phillips",
    location: "Singapore",
    avatar: "/avatars/harry-phillips.webp",
  },
  {
    rating: 5,
    title: "Professional and Personable",
    body: "The team at Estatein made us feel like family throughout the home buying process. We couldn't be happier with their work.",
    name: "William McCoy",
    location: "USA, Chicago",
    avatar: "/avatars/william-mccoy.webp",
  },
  {
    rating: 5,
    title: "Seamless Process",
    body: "With Estatein's expertise, finding and purchasing our dream home was easy and stress-free. We highly recommend them.",
    name: "Ralph Dixon",
    location: "Canada, Vancouver",
    avatar: "/avatars/ralph-dixon.webp",
  },
  {
    rating: 5,
    title: "Outstanding Agents",
    body: "The agents at Estatein are true professionals. Their market knowledge and negotiation skills are second to none.",
    name: "Trevor Fox",
    location: "UK, Manchester",
    avatar: "/avatars/trevor-fox.webp",
  },
  {
    rating: 5,
    title: "Amazing Experience",
    body: "We had an absolutely amazing experience with Estatein. Their team made the entire process smooth and stress-free. We highly recommend them!",
    name: "Chad Ford",
    location: "Canada, Toronto",
    avatar: "/avatars/chad-ford.webp",
  },
  {
    rating: 5,
    title: "Fantastic Experience",
    body: "Estatein made the home buying process stress-free and enjoyable. Their agents are true professionals who know the market inside and out.",
    name: "John Mans",
    location: "USA, New York",
    avatar: "/avatars/john-mans.webp",
  },
];
