export const LOCATIONS = [
  "arizona",
  "california",
  "florida",
  "hawaii",
  "massachusetts",
  "michigan",
  "nebraska",
  "nevada",
  "new mexico",
  "new york",
  "ohio",
  "texas",
  "washington",
] as const;
